#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PersonelTakipDB")]
	public partial class PersonelDataClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAylar_Tablo(Aylar_Tablo instance);
    partial void UpdateAylar_Tablo(Aylar_Tablo instance);
    partial void DeleteAylar_Tablo(Aylar_Tablo instance);
    partial void InsertDepartman_Tablo(Departman_Tablo instance);
    partial void UpdateDepartman_Tablo(Departman_Tablo instance);
    partial void DeleteDepartman_Tablo(Departman_Tablo instance);
    partial void InsertIS_Tablo(IS_Tablo instance);
    partial void UpdateIS_Tablo(IS_Tablo instance);
    partial void DeleteIS_Tablo(IS_Tablo instance);
    partial void InsertIsDurum_Tablo(IsDurum_Tablo instance);
    partial void UpdateIsDurum_Tablo(IsDurum_Tablo instance);
    partial void DeleteIsDurum_Tablo(IsDurum_Tablo instance);
    partial void InsertIzin_Tablo(Izin_Tablo instance);
    partial void UpdateIzin_Tablo(Izin_Tablo instance);
    partial void DeleteIzin_Tablo(Izin_Tablo instance);
    partial void InsertIzinDurum_Tablo(IzinDurum_Tablo instance);
    partial void UpdateIzinDurum_Tablo(IzinDurum_Tablo instance);
    partial void DeleteIzinDurum_Tablo(IzinDurum_Tablo instance);
    partial void InsertMaas_Tablo(Maas_Tablo instance);
    partial void UpdateMaas_Tablo(Maas_Tablo instance);
    partial void DeleteMaas_Tablo(Maas_Tablo instance);
    partial void InsertPersonel_Tablo(Personel_Tablo instance);
    partial void UpdatePersonel_Tablo(Personel_Tablo instance);
    partial void DeletePersonel_Tablo(Personel_Tablo instance);
    partial void InsertPozisyon_Tablo(Pozisyon_Tablo instance);
    partial void UpdatePozisyon_Tablo(Pozisyon_Tablo instance);
    partial void DeletePozisyon_Tablo(Pozisyon_Tablo instance);
    #endregion
		
		public PersonelDataClassDataContext() : 
				base(global::DAL.Properties.Settings.Default.PersonelTakipDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PersonelDataClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonelDataClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonelDataClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonelDataClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Aylar_Tablo> Aylar_Tablos
		{
			get
			{
				return this.GetTable<Aylar_Tablo>();
			}
		}
		
		public System.Data.Linq.Table<Departman_Tablo> Departman_Tablos
		{
			get
			{
				return this.GetTable<Departman_Tablo>();
			}
		}
		
		public System.Data.Linq.Table<IS_Tablo> IS_Tablos
		{
			get
			{
				return this.GetTable<IS_Tablo>();
			}
		}
		
		public System.Data.Linq.Table<IsDurum_Tablo> IsDurum_Tablos
		{
			get
			{
				return this.GetTable<IsDurum_Tablo>();
			}
		}
		
		public System.Data.Linq.Table<Izin_Tablo> Izin_Tablos
		{
			get
			{
				return this.GetTable<Izin_Tablo>();
			}
		}
		
		public System.Data.Linq.Table<IzinDurum_Tablo> IzinDurum_Tablos
		{
			get
			{
				return this.GetTable<IzinDurum_Tablo>();
			}
		}
		
		public System.Data.Linq.Table<Maas_Tablo> Maas_Tablos
		{
			get
			{
				return this.GetTable<Maas_Tablo>();
			}
		}
		
		public System.Data.Linq.Table<Personel_Tablo> Personel_Tablos
		{
			get
			{
				return this.GetTable<Personel_Tablo>();
			}
		}
		
		public System.Data.Linq.Table<Pozisyon_Tablo> Pozisyon_Tablos
		{
			get
			{
				return this.GetTable<Pozisyon_Tablo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Aylar_Tablo")]
	public partial class Aylar_Tablo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAyChanging(string value);
    partial void OnAyChanged();
    #endregion
		
		public Aylar_Tablo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ay", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Ay
		{
			get
			{
				return this._Ay;
			}
			set
			{
				if ((this._Ay != value))
				{
					this.OnAyChanging(value);
					this.SendPropertyChanging();
					this._Ay = value;
					this.SendPropertyChanged("Ay");
					this.OnAyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departman_Tablo")]
	public partial class Departman_Tablo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DepartmanAD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDepartmanADChanging(string value);
    partial void OnDepartmanADChanged();
    #endregion
		
		public Departman_Tablo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmanAD", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DepartmanAD
		{
			get
			{
				return this._DepartmanAD;
			}
			set
			{
				if ((this._DepartmanAD != value))
				{
					this.OnDepartmanADChanging(value);
					this.SendPropertyChanging();
					this._DepartmanAD = value;
					this.SendPropertyChanged("DepartmanAD");
					this.OnDepartmanADChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IS_Tablo")]
	public partial class IS_Tablo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _CalisanID;
		
		private string _Baslik;
		
		private string _Icerik;
		
		private System.DateTime _IsBaslamaTarihi;
		
		private System.DateTime _IsBitisTarihi;
		
		private int _IsDurumID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCalisanIDChanging(int value);
    partial void OnCalisanIDChanged();
    partial void OnBaslikChanging(string value);
    partial void OnBaslikChanged();
    partial void OnIcerikChanging(string value);
    partial void OnIcerikChanged();
    partial void OnIsBaslamaTarihiChanging(System.DateTime value);
    partial void OnIsBaslamaTarihiChanged();
    partial void OnIsBitisTarihiChanging(System.DateTime value);
    partial void OnIsBitisTarihiChanged();
    partial void OnIsDurumIDChanging(int value);
    partial void OnIsDurumIDChanged();
    #endregion
		
		public IS_Tablo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalisanID", DbType="Int NOT NULL")]
		public int CalisanID
		{
			get
			{
				return this._CalisanID;
			}
			set
			{
				if ((this._CalisanID != value))
				{
					this.OnCalisanIDChanging(value);
					this.SendPropertyChanging();
					this._CalisanID = value;
					this.SendPropertyChanged("CalisanID");
					this.OnCalisanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Baslik", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Baslik
		{
			get
			{
				return this._Baslik;
			}
			set
			{
				if ((this._Baslik != value))
				{
					this.OnBaslikChanging(value);
					this.SendPropertyChanging();
					this._Baslik = value;
					this.SendPropertyChanged("Baslik");
					this.OnBaslikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icerik", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Icerik
		{
			get
			{
				return this._Icerik;
			}
			set
			{
				if ((this._Icerik != value))
				{
					this.OnIcerikChanging(value);
					this.SendPropertyChanging();
					this._Icerik = value;
					this.SendPropertyChanged("Icerik");
					this.OnIcerikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBaslamaTarihi", DbType="Date NOT NULL")]
		public System.DateTime IsBaslamaTarihi
		{
			get
			{
				return this._IsBaslamaTarihi;
			}
			set
			{
				if ((this._IsBaslamaTarihi != value))
				{
					this.OnIsBaslamaTarihiChanging(value);
					this.SendPropertyChanging();
					this._IsBaslamaTarihi = value;
					this.SendPropertyChanged("IsBaslamaTarihi");
					this.OnIsBaslamaTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBitisTarihi", DbType="Date NOT NULL")]
		public System.DateTime IsBitisTarihi
		{
			get
			{
				return this._IsBitisTarihi;
			}
			set
			{
				if ((this._IsBitisTarihi != value))
				{
					this.OnIsBitisTarihiChanging(value);
					this.SendPropertyChanging();
					this._IsBitisTarihi = value;
					this.SendPropertyChanged("IsBitisTarihi");
					this.OnIsBitisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDurumID", DbType="Int NOT NULL")]
		public int IsDurumID
		{
			get
			{
				return this._IsDurumID;
			}
			set
			{
				if ((this._IsDurumID != value))
				{
					this.OnIsDurumIDChanging(value);
					this.SendPropertyChanging();
					this._IsDurumID = value;
					this.SendPropertyChanged("IsDurumID");
					this.OnIsDurumIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IsDurum_Tablo")]
	public partial class IsDurum_Tablo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _IsDurumAd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIsDurumAdChanging(string value);
    partial void OnIsDurumAdChanged();
    #endregion
		
		public IsDurum_Tablo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDurumAd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IsDurumAd
		{
			get
			{
				return this._IsDurumAd;
			}
			set
			{
				if ((this._IsDurumAd != value))
				{
					this.OnIsDurumAdChanging(value);
					this.SendPropertyChanging();
					this._IsDurumAd = value;
					this.SendPropertyChanged("IsDurumAd");
					this.OnIsDurumAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Izin_Tablo")]
	public partial class Izin_Tablo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _CalisanID;
		
		private System.DateTime _IzinBaslangicTarihi;
		
		private System.DateTime _IzinBitisTarihi;
		
		private string _Aciklama;
		
		private int _Sure;
		
		private int _IzinDurumID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCalisanIDChanging(int value);
    partial void OnCalisanIDChanged();
    partial void OnIzinBaslangicTarihiChanging(System.DateTime value);
    partial void OnIzinBaslangicTarihiChanged();
    partial void OnIzinBitisTarihiChanging(System.DateTime value);
    partial void OnIzinBitisTarihiChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnSureChanging(int value);
    partial void OnSureChanged();
    partial void OnIzinDurumIDChanging(int value);
    partial void OnIzinDurumIDChanged();
    #endregion
		
		public Izin_Tablo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalisanID", DbType="Int NOT NULL")]
		public int CalisanID
		{
			get
			{
				return this._CalisanID;
			}
			set
			{
				if ((this._CalisanID != value))
				{
					this.OnCalisanIDChanging(value);
					this.SendPropertyChanging();
					this._CalisanID = value;
					this.SendPropertyChanged("CalisanID");
					this.OnCalisanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinBaslangicTarihi", DbType="Date NOT NULL")]
		public System.DateTime IzinBaslangicTarihi
		{
			get
			{
				return this._IzinBaslangicTarihi;
			}
			set
			{
				if ((this._IzinBaslangicTarihi != value))
				{
					this.OnIzinBaslangicTarihiChanging(value);
					this.SendPropertyChanging();
					this._IzinBaslangicTarihi = value;
					this.SendPropertyChanged("IzinBaslangicTarihi");
					this.OnIzinBaslangicTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinBitisTarihi", DbType="Date NOT NULL")]
		public System.DateTime IzinBitisTarihi
		{
			get
			{
				return this._IzinBitisTarihi;
			}
			set
			{
				if ((this._IzinBitisTarihi != value))
				{
					this.OnIzinBitisTarihiChanging(value);
					this.SendPropertyChanging();
					this._IzinBitisTarihi = value;
					this.SendPropertyChanged("IzinBitisTarihi");
					this.OnIzinBitisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sure", DbType="Int NOT NULL")]
		public int Sure
		{
			get
			{
				return this._Sure;
			}
			set
			{
				if ((this._Sure != value))
				{
					this.OnSureChanging(value);
					this.SendPropertyChanging();
					this._Sure = value;
					this.SendPropertyChanged("Sure");
					this.OnSureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinDurumID", DbType="Int NOT NULL")]
		public int IzinDurumID
		{
			get
			{
				return this._IzinDurumID;
			}
			set
			{
				if ((this._IzinDurumID != value))
				{
					this.OnIzinDurumIDChanging(value);
					this.SendPropertyChanging();
					this._IzinDurumID = value;
					this.SendPropertyChanged("IzinDurumID");
					this.OnIzinDurumIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IzinDurum_Tablo")]
	public partial class IzinDurum_Tablo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _IzinDurumAd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIzinDurumAdChanging(string value);
    partial void OnIzinDurumAdChanged();
    #endregion
		
		public IzinDurum_Tablo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinDurumAd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IzinDurumAd
		{
			get
			{
				return this._IzinDurumAd;
			}
			set
			{
				if ((this._IzinDurumAd != value))
				{
					this.OnIzinDurumAdChanging(value);
					this.SendPropertyChanging();
					this._IzinDurumAd = value;
					this.SendPropertyChanged("IzinDurumAd");
					this.OnIzinDurumAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Maas_Tablo")]
	public partial class Maas_Tablo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _CalisanID;
		
		private int _Tutar;
		
		private int _YIL;
		
		private int _AY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCalisanIDChanging(int value);
    partial void OnCalisanIDChanged();
    partial void OnTutarChanging(int value);
    partial void OnTutarChanged();
    partial void OnYILChanging(int value);
    partial void OnYILChanged();
    partial void OnAYChanging(int value);
    partial void OnAYChanged();
    #endregion
		
		public Maas_Tablo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalisanID", DbType="Int NOT NULL")]
		public int CalisanID
		{
			get
			{
				return this._CalisanID;
			}
			set
			{
				if ((this._CalisanID != value))
				{
					this.OnCalisanIDChanging(value);
					this.SendPropertyChanging();
					this._CalisanID = value;
					this.SendPropertyChanged("CalisanID");
					this.OnCalisanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tutar", DbType="Int NOT NULL")]
		public int Tutar
		{
			get
			{
				return this._Tutar;
			}
			set
			{
				if ((this._Tutar != value))
				{
					this.OnTutarChanging(value);
					this.SendPropertyChanging();
					this._Tutar = value;
					this.SendPropertyChanged("Tutar");
					this.OnTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YIL", DbType="Int NOT NULL")]
		public int YIL
		{
			get
			{
				return this._YIL;
			}
			set
			{
				if ((this._YIL != value))
				{
					this.OnYILChanging(value);
					this.SendPropertyChanging();
					this._YIL = value;
					this.SendPropertyChanged("YIL");
					this.OnYILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AY", DbType="Int NOT NULL")]
		public int AY
		{
			get
			{
				return this._AY;
			}
			set
			{
				if ((this._AY != value))
				{
					this.OnAYChanging(value);
					this.SendPropertyChanging();
					this._AY = value;
					this.SendPropertyChanged("AY");
					this.OnAYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Personel_Tablo")]
	public partial class Personel_Tablo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _KullaniciNo;
		
		private string _Ad;
		
		private string _Soyad;
		
		private string _Resim;
		
		private int _DepartmanID;
		
		private int _PozisyonID;
		
		private int _Maas;
		
		private System.DateTime _DogumGunu;
		
		private string _Adres;
		
		private string _Sifre;
		
		private bool _isAdmin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKullaniciNoChanging(int value);
    partial void OnKullaniciNoChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnResimChanging(string value);
    partial void OnResimChanged();
    partial void OnDepartmanIDChanging(int value);
    partial void OnDepartmanIDChanged();
    partial void OnPozisyonIDChanging(int value);
    partial void OnPozisyonIDChanged();
    partial void OnMaasChanging(int value);
    partial void OnMaasChanged();
    partial void OnDogumGunuChanging(System.DateTime value);
    partial void OnDogumGunuChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    partial void OnisAdminChanging(bool value);
    partial void OnisAdminChanged();
    #endregion
		
		public Personel_Tablo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciNo", DbType="Int NOT NULL")]
		public int KullaniciNo
		{
			get
			{
				return this._KullaniciNo;
			}
			set
			{
				if ((this._KullaniciNo != value))
				{
					this.OnKullaniciNoChanging(value);
					this.SendPropertyChanging();
					this._KullaniciNo = value;
					this.SendPropertyChanged("KullaniciNo");
					this.OnKullaniciNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Resim
		{
			get
			{
				return this._Resim;
			}
			set
			{
				if ((this._Resim != value))
				{
					this.OnResimChanging(value);
					this.SendPropertyChanging();
					this._Resim = value;
					this.SendPropertyChanged("Resim");
					this.OnResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmanID", DbType="Int NOT NULL")]
		public int DepartmanID
		{
			get
			{
				return this._DepartmanID;
			}
			set
			{
				if ((this._DepartmanID != value))
				{
					this.OnDepartmanIDChanging(value);
					this.SendPropertyChanging();
					this._DepartmanID = value;
					this.SendPropertyChanged("DepartmanID");
					this.OnDepartmanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PozisyonID", DbType="Int NOT NULL")]
		public int PozisyonID
		{
			get
			{
				return this._PozisyonID;
			}
			set
			{
				if ((this._PozisyonID != value))
				{
					this.OnPozisyonIDChanging(value);
					this.SendPropertyChanging();
					this._PozisyonID = value;
					this.SendPropertyChanged("PozisyonID");
					this.OnPozisyonIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maas", DbType="Int NOT NULL")]
		public int Maas
		{
			get
			{
				return this._Maas;
			}
			set
			{
				if ((this._Maas != value))
				{
					this.OnMaasChanging(value);
					this.SendPropertyChanging();
					this._Maas = value;
					this.SendPropertyChanged("Maas");
					this.OnMaasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DogumGunu", DbType="Date NOT NULL")]
		public System.DateTime DogumGunu
		{
			get
			{
				return this._DogumGunu;
			}
			set
			{
				if ((this._DogumGunu != value))
				{
					this.OnDogumGunuChanging(value);
					this.SendPropertyChanging();
					this._DogumGunu = value;
					this.SendPropertyChanged("DogumGunu");
					this.OnDogumGunuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isAdmin", DbType="Bit NOT NULL")]
		public bool isAdmin
		{
			get
			{
				return this._isAdmin;
			}
			set
			{
				if ((this._isAdmin != value))
				{
					this.OnisAdminChanging(value);
					this.SendPropertyChanging();
					this._isAdmin = value;
					this.SendPropertyChanged("isAdmin");
					this.OnisAdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pozisyon_Tablo")]
	public partial class Pozisyon_Tablo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PozisyonAd;
		
		private int _DepartmanID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPozisyonAdChanging(string value);
    partial void OnPozisyonAdChanged();
    partial void OnDepartmanIDChanging(int value);
    partial void OnDepartmanIDChanged();
    #endregion
		
		public Pozisyon_Tablo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PozisyonAd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PozisyonAd
		{
			get
			{
				return this._PozisyonAd;
			}
			set
			{
				if ((this._PozisyonAd != value))
				{
					this.OnPozisyonAdChanging(value);
					this.SendPropertyChanging();
					this._PozisyonAd = value;
					this.SendPropertyChanged("PozisyonAd");
					this.OnPozisyonAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmanID", DbType="Int NOT NULL")]
		public int DepartmanID
		{
			get
			{
				return this._DepartmanID;
			}
			set
			{
				if ((this._DepartmanID != value))
				{
					this.OnDepartmanIDChanging(value);
					this.SendPropertyChanging();
					this._DepartmanID = value;
					this.SendPropertyChanged("DepartmanID");
					this.OnDepartmanIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
